FROM node:14.15.4-alpine as builder

LABEL maintainer="lizahung1008@gmail.com"

WORKDIR /app

COPY package*.json ./

RUN npm install -f

COPY . .

RUN npm run build


FROM nginx:stable-alpine as production-stage

COPY ./default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
