FROM adoptopenjdk/openjdk11:alpine

LABEL maintainer="lizahung1008@gmail.com"

ADD ./adoption-0.0.1-SNAPSHOT.jar app.jar

RUN sh -c 'touch /app.jar'

ENTRYPOINT ["java", "-Dfile.encoding=UTF-8", "-jar", "/app.jar"]
